#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    --role
    CREATE USER $APP_DB_USER PASSWORD '$APP_DB_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
    CREATE DATABASE crm OWNER = $APP_DB_USER ENCODING = 'UTF8';
    CREATE SCHEMA admin;
    CREATE SCHEMA client;
    --GRANT ALL PRIVILEGES ON DATABASE crm TO $APP_DB_USER;
EOSQL

#psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "eurochem" <<-EOSQL
#    --schema
#    CREATE SCHEMA IF NOT EXISTS privoma AUTHORIZATION $APP_DB_USER;
#
#    --grant
#    GRANT CONNECT ON DATABASE eurochem TO $APP_DB_USER;

