version: '3.4'

services:

  crm-database:
    build:
      context: ./
      dockerfile: ./database/Dockerfile
    env_file:
      - ./docker.env
    image: crm-database
    container_name: crm-database
    ports:
      - 5438:5432